export const CATEGORIES = [
  {
    key: 'academic',
    label: 'Academic',
    events: [
      '🩺 Basic Life Support Workshop',
      '🧠 Cine-Seminar (Psychiatry Workshop)',
      '💬 Doc-Talk',
      '📝 Preclinical Quiz',
      '🔬 Paraclinical Quiz',
      '🏥 Clinical Quiz',
      '📋 Case Presentation',
    ],
  },
  {
    key: 'literary',
    label: 'Literary',
    events: [
      '🗣️ Agora (Debate)',
      '✒️ Hridaya (Poetry, Shayari & Elocution)',
      '🐝 Spell Bee',
      '📺 TMKOC Quiz',
      '🍿 Pop-Culture Quiz',
      '🧠 General Quiz',
    ],
  },
  {
    key: 'informal',
    label: 'Informal',
    events: [
      '👨‍👩‍👧‍👦 Family Feud',
      '🎯 Dare to Dart',
      '💪 Push Up Challenge',
      '🤝 Arm Wrestling',
      '🗺️ Treasure Hunt',
      '🎬 Film Reenactment',
      '🍳 Cooking',
    ],
  },
  {
    key: 'sports',
    label: 'Sports',
    events: [
      '🏏 Cricket',
      '⚽ Football',
      '🏐 Volleyball',
      '🏸 Badminton',
      '🤼 Kabaddi',
      '🪢 Tug of War',
      '♟️ Chess',
      '🏓 Table Tennis',
      '🎯 Carrom',
      '🏃 Athletics',
      "🧩 Rubik's Mania",
      '⚾ Mix Cricket',
      '🎮 BGMI',
      '🏃‍♂️ Kho Kho',
    ],
  },
  {
    key: 'cultural',
    label: 'Cultural',
    events: [
      '🎤 Swarmay (Singing)',
      '💃 Flamenco (Dancing)',
      '🎥 Cinematica (Film Making)',
      '📱 Montage (Reel Making)',
      '📸 Lensanity (Photography)',
      '🌟 Got Talent',
      '😂 MemeCentral (Meme Competition)',
      '🎬 Stardust (Bollywood Recreation)',
      '🕺 Groove Gala (On the Spot Dance)',
      '🎭 Dharohar (Folklore)',
      '🎶 Antakshari',
      '🤫 Dumb Charades',
      '🪑 Musical Chairs',
      '🍿 Movie Night',
      '👗 Venust (Fashion Show)',
      '✨ Prom Night',
    ],
  },
  {
    key: 'art',
    label: 'Art',
    events: [
      '🎨 Chitraganga (Painting)',
      '🛣️ Lok Natya (Nukkad Natak)',
      '🖍️ Doodle Dreams (Doodle Art)',
      '🏺 Sculpture Spectacle (Clay Art)',
      '✒️ Tattoo Titans (Tattoo Art)',
      '🌿 Mehendi Delights (Mehendi)',
      '🌸 Aripan (Rangoli)',
      '♻️ Recycled Wonders (Waste Art)',
      '💻 Cyber-Creation (Digital Art)',
      '👕 Tee-Splash (T-Shirt Painting)',
      '👨‍⚕️ Clinical Cartoons (Medical Caricature)',
      '🎭 Magic Mask (Face Painting)',
    ],
  },
];

export const ALL_EVENTS_FLAT = CATEGORIES.flatMap((c) =>
  c.events.map((e) => ({ name: e, cat: c.label }))
);

export const TOTAL_EVENTS = 70; // official flyer figure
